service: plaid-go-lambda
frameworkVersion: ">=1.28.0"

provider:
    name: aws
    runtime: go1.x
    region: us-east-1
    stage: dev # 배포할거면 dev, local에서 테스트할거면 local

functions:
    api:
        # Type: AWS::Serverless::Api
        # Properties:
        #     Cors:
        #         AllowOrigin: "'*'"
        #         AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        #         AllowHeaders: "'X-Amz-Date,X-Api-Key,X-Amz-Security-Token,X-Requested-With,X-Auth-Token,Referer,User-Agent,Origin,Content-Type,Authorization,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
        handler: bin/main # 배포할때는 bin/main, local에서는 main.go
        events:
            - httpApi:
                  path: /
                  method: get
            - httpApi:
                  path: /create_link_token
                  method: post
            - httpApi:
                  path: /get_access_token
                  method: post
        # environment:
        #     PLATY_ID_TOKEN_TABLE: !Ref PlaidIdTokenTable

    # sendToQueue:
    #     handler: bin/sendToQueue
    #     environment:
    #         QUEUE_URL: !GetAtt Plaid-SQS.Arn
    #     events:
    #         - httpApi:
    #               path: /send-to-queue
    #               method: post

package:
    patterns:
        - "!*/**" # ! menas excluding. exclude everyting and push bin/main file to aws
        - bin/main

plugins:
    - serverless-offline

custom:
    serverless-offline:
        noPrependStageInUrl: true
# resources:
#     Resources:
#         Plaid-SQS:
#             Type: AWS::SQS::Queue
#             Properties:
#                 QueueName: Plaid-SQS
#         PlaidIdTokenTable:
#             Type: AWS::DynamoDB::Table
#             Properties:
#                 TableName: PlaidIdTokenTable
#                 AttributeDefinitions:
#                     - AttributeName: id
#                       AttributeType: S
#                 KeySchema:
#                     - AttributeName: id
#                       KeyType: HASH
#                 ProvisionedThroughput:
#                     ReadCapacityUnits: 5
#                     WriteCapacityUnits: 5
