import "./globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Navbar } from "@/components/Navbar";
import QueryProvider from "@/lib/QueryProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <QueryProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
                            <Navbar />
                            {children}
                        </div>
                    </ThemeProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
